server:
  port: 8080

spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: Asish@6292
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:9296

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
